---
- name: "Is pdf-parser available?"
  stat:
    path: ~/bin/pdf-parser
  register: is_pdfparser

- name: "DL source code"
  when: is_pdfparser.stat.exists == False
  get_url:
    url: https://didierstevens.com/files/software/pdf-parser_V0_6_6.zip
    dest: "{{ TOOLS_DIRECTORY_FORENSICS }}/pdf-parser.zip"
    validate_certs: False

- name: "Extract zip file"
  when: is_pdfparser.stat.exists == False
  unarchive:
    src: "{{ TOOLS_DIRECTORY_FORENSICS }}/pdf-parser.zip"
    dest: "{{ TOOLS_DIRECTORY_FORENSICS }}/" 

- name: "Change pdf-parser privilege"
  when: is_pdfparser.stat.exists == False
  file:
    src: "{{ TOOLS_DIRECTORY_FORENSICS }}/pdf-parser.py"
    dest: ~/bin/pdf-parser
    mode: 0755
    state: link

