---
- name: "Change apt mirror url"
  become: true
  replace: >-
    dest='/etc/apt/sources.list'
    regexp='archive.ubuntu.com/ubuntu'
    replace='ftp.iij.ad.jp/pub/linux/ubuntu/archive'

- name: "Install the common apt packages"
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - git
    - zsh
    - vim
    - build-essential
    - python
    - python-pip
    - python3
    - python3-pip
    - make
    - unzip

- name: "Create directory to store tools"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/bin/
    - "{{ TOOLS_DIRECTORY_CRYPTO }}"
    - "{{ TOOLS_DIRECTORY_REVERSING }}"
    - "{{ TOOLS_DIRECTORY_FORENSICS }}"
    - "{{ TOOLS_DIRECTORY_MISC }}"
    - "{{ TOOLS_DIRECTORY_PROGRAMMING }}"

- name: "Check PATH configuration at ~/.bash_profile"
  register: is_path
  shell: grep -e '~/bin' ~/.bash_profile
  failed_when: is_path.rc != 0
  ignore_errors: true

- name: "Add PATHs at ~/.bash_profile"
  shell: echo 'export PATH=~/bin:$PATH' >> ~/.bash_profile
  when: is_path.rc != 0
