---
- name: "Is checksec available?"
  stat:
    path: ~/bin/checksec
  register: is_checksec

- name: "Get repository from GitHub"
  when: is_checksec.stat.exists == False
  git:
    repo: https://github.com/slimm609/checksec.sh
    dest: "{{ TOOLS_DIRECTORY_REVERSING }}/checksec"

- name: " Link checksec to ~/bin directory"
  file:
    src: "{{ TOOLS_DIRECTORY_REVERSING }}/checksec/checksec"
    dest: "~/bin/checksec"
    state: link

