---
- name: "Is msieve available?"
  stat:
    path: ~/bin/msieve
  register: is_msieve

- name: "Install dependencies for msieve"
  become: true
  when: is_msieve.stat.exists == False
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libgmp3-dev
    - libgmp-dev
    - libz-dev

- name: "DL via URL"
  when: is_msieve.stat.exists == False
  get_url:
    url: "https://downloads.sourceforge.net/project/msieve/msieve/Msieve%20v1.53/msieve153_src.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmsieve%2Ffiles%2Fmsieve%2F&ts=1487435392&use_mirror=jaist"
    dest: "{{ TOOLS_DIRECTORY_CRYPTO }}/msieve.tar.gz"

- name: "Extract source code"
  when: is_msieve.stat.exists == False
  unarchive:
    src: "{{ TOOLS_DIRECTORY_CRYPTO }}/msieve.tar.gz"
    dest: "{{ TOOLS_DIRECTORY_CRYPTO }}/"
    remote_src: True

- name: "Build msieve"
  when: is_msieve.stat.exists == False
  command: make all
  args:
    chdir: "{{ TOOLS_DIRECTORY_CRYPTO }}/msieve-1.53"

- name: "Link msieve to ~/bin"
  file:
    src: "{{ TOOLS_DIRECTORY_CRYPTO }}/msieve-1.53/msieve"
    dest: ~/bin/msieve
    state: link
